const FO_CONFIG = {
  PLATFORM_NAME: 'Family Office CIO Platform',
  PLATFORM_VERSION: 'v1.0.0',
  RELEASE_NAME: 'Operational Analytics',
  BASELINE: 'CB-002',
  BUILD: '2026.07.08.001',
  ENVIRONMENT: 'Production Candidate',

  ENGINE_NAME: 'Family Office CIO Orchestrator',
  ENGINE_VERSION: 'v3.0.0',

  LEDGER_SPREADSHEET_ID: '1_NIOTk1bC0QilRDfo8nKshoLh9Xdm1FWdDybsNvAo8k',
  DASHBOARD_SPREADSHEET_ID: '13jHJ0N1Gzbia7B4FIHkdTqf2tCp1tkXSFicQ2ti8M1w',

  BASE_CURRENCY: 'CAD',
  TIMEZONE: Session.getScriptTimeZone()
};

const FO_SHEETS = {
  AUTOMATION_LOG: 'Automation Log',
  PLATFORM_HEALTH: 'Platform Health',
  PORTFOLIO_MASTER: 'Portfolio Master',
  PORTFOLIO_DASHBOARD: 'Portfolio Dashboard',
  LEDGER: 'Ledger',
  RECOMMENDATION_LEDGER: 'Recommendation Ledger',
  RECOMMENDATION_PERFORMANCE: 'Recommendation Performance',
  PORTFOLIO_ATTRIBUTION: 'Portfolio Attribution',
  KNOWLEDGE_BASE: 'Knowledge Base',
  EXECUTIVE_DASHBOARD: 'Executive Dashboard',
  DAILY_CIO_REPORT: 'Daily CIO Report',
  WEEKLY_EXECUTIVE_REPORT: 'Weekly Executive Report',
  INVESTMENT_COMMITTEE_SUMMARY: 'Investment Committee Summary',
  BUY_ZONE_RULES: 'Buy Zone Rules',
  BUY_ZONE_TARGETS: 'Buy Zone Targets',
  CONVICTION_RULES: 'Conviction Rules',
  BUY_ZONE_INTELLIGENCE: 'Buy Zone Intelligence',
  BUY_ZONE_EXECUTIVE_SUMMARY: 'Buy Zone Executive Summary',
  INVESTMENT_DECISION_SUPPORT: 'Investment Decision Support',
  INVESTMENT_DECISION_HISTORY: 'Investment Decision History',
  DECISION_HISTORY_POLICY: 'Decision History Policy',
  INVESTMENT_TRENDS: 'Investment Trends',
  INVESTMENT_TREND_SUMMARY: 'Investment Trend Summary',
  MATERIALITY_POLICY: 'Materiality Policy',
  MATERIALITY_EVENTS: 'Materiality Events'
};

const FO_REQUIRED_DASHBOARD_SHEETS = [
  FO_SHEETS.PORTFOLIO_MASTER,
  FO_SHEETS.PORTFOLIO_DASHBOARD,
  FO_SHEETS.LEDGER,
  FO_SHEETS.RECOMMENDATION_LEDGER,
  FO_SHEETS.RECOMMENDATION_PERFORMANCE,
  FO_SHEETS.PORTFOLIO_ATTRIBUTION,
  FO_SHEETS.KNOWLEDGE_BASE,
  FO_SHEETS.EXECUTIVE_DASHBOARD,
  FO_SHEETS.DAILY_CIO_REPORT,
  FO_SHEETS.WEEKLY_EXECUTIVE_REPORT,
  FO_SHEETS.INVESTMENT_COMMITTEE_SUMMARY,
  FO_SHEETS.BUY_ZONE_RULES,
  FO_SHEETS.BUY_ZONE_TARGETS,
  FO_SHEETS.CONVICTION_RULES,
  FO_SHEETS.BUY_ZONE_INTELLIGENCE,
  FO_SHEETS.BUY_ZONE_EXECUTIVE_SUMMARY,
  FO_SHEETS.INVESTMENT_DECISION_SUPPORT,
  FO_SHEETS.INVESTMENT_DECISION_HISTORY,
  FO_SHEETS.DECISION_HISTORY_POLICY,
  FO_SHEETS.INVESTMENT_TRENDS,
  FO_SHEETS.INVESTMENT_TREND_SUMMARY,
  FO_SHEETS.MATERIALITY_POLICY,
  FO_SHEETS.MATERIALITY_EVENTS
];