/**
 * Legacy Phase B compatibility service.
 */

const FO_PHASE_B_TABS = {
  RECOMMENDATIONS: 'Recommendations',
  MARKET_ACCESS: 'Canadian Market Access Library',
  ORCHESTRATION_LOG: 'Orchestration Log',
  REPORT_ARCHIVE: 'Report Archive',
  DATA_INTEGRITY: 'Data Integrity'
};

function foSetupPhaseB() {
  const ledger = foLedger_();

  foEnsureSheet_(ledger, FO_PHASE_B_TABS.ORCHESTRATION_LOG, [
    'Timestamp', 'Run ID', 'Channel', 'Action', 'Status', 'Message', 'Version'
  ]);

  foEnsureSheet_(ledger, FO_PHASE_B_TABS.REPORT_ARCHIVE, [
    'Timestamp', 'Report ID', 'Report Type', 'Title',
    'Materiality Score', 'Action Plan Changed?', 'Report Link', 'Notes'
  ]);

  foEnsureSheet_(ledger, FO_PHASE_B_TABS.DATA_INTEGRITY, [
    'Timestamp', 'Check Type', 'Status', 'Details', 'Resolved?'
  ]);

  foEnsureSheet_(ledger, FO_PHASE_B_TABS.MARKET_ACCESS, [
    'Ticker', 'Company', 'Native Listing', 'Canadian Common Share',
    'Canadian CDR', 'Canadian ETF Alternative', 'Preferred Vehicle',
    'Market Access Type', 'Last Reviewed', 'Liquidity Assessment',
    'Tracking Assessment', 'CIO Notes'
  ]);

  foInfo_('PhaseBService', 'Setup', 'Phase B service layer initialized.');

  return { status: 'SUCCESS', sheetsEnsured: 4 };
}

function foRunPhaseBSmokeTest() {
  const module = 'PhaseBService';

  try {
    foInfo_(module, 'Start', 'Phase B smoke test started.');

    foSetupPhaseB();
    foSeedKnownCDRs();

    foAppendRecommendationEvent({
      channel: 'smoke-test',
      investment: 'Sample Only',
      ticker: 'SAMPLE',
      preferredVehicle: 'Sample Vehicle',
      marketAccessType: 'Test',
      accounts: 'TFSA',
      recommendationCategory: 'Watch for Trigger',
      statusAtIssuance: 'Sample',
      currentStatus: 'Sample',
      materialityScore: 0,
      convictionScore: 0,
      buyZoneConfidence: 0,
      cioReadiness: 0,
      plannedReviewTrigger: 'Manual Review',
      rationale: 'Smoke test for Phase B service layer.',
      sourceNotes: 'Generated by Apps Script smoke test.'
    });

    foAppendDashboardMetric({
      name: 'Phase B Smoke Test',
      value: 'Completed',
      status: 'PASS',
      notes: 'Dashboard write path validated.'
    });

    const integrity = foRunLedgerIntegrityCheck();
    const reportId = foArchiveReport({
      reportType: 'Smoke Test',
      title: 'Phase B Orchestration Smoke Test',
      materialityScore: 0,
      actionPlanChanged: 'No',
      notes: 'Validated service calls.'
    });

    foInfo_(module, 'Complete', 'Phase B smoke test completed.');

    return {
      status: 'SUCCESS',
      integrity: integrity.status,
      reportId: reportId
    };
  } catch (error) {
    foError_(module, 'Failure', error);
    throw error;
  }
}
